name: TestHazem
favicon: null
layout_spectrum: 0.45558679150417447
typography_spectrum: 0.3130129366181791
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5791660309769213
  lightness: 0.3877502139657736
  saturation: 0.13117094850167632
  rhythmicContrast: 0.0035360236652195454
purpose: []
